name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php-versions }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      uses: ramsey/composer-install@v1
      with:
        composer-options: "--prefer-dist"

    - name: Run PHPUnit
      run: vendor/bin/phpunit

    - name: Psalm
      if: ${{ matrix.php-versions == '7.4' }}
      run: ./vendor/bin/psalm --show-info=false --threads=8 --diff

    - name: Run PHPCS
      run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 src modules woocommerce-paypal-payments.php --extensions=php
